-- Generated by scripts/build-zip-geo.mjs. US ZIP centroids for distance matching and ZIP->state lookup.
CREATE TABLE IF NOT EXISTS zip_geo (
  zip TEXT PRIMARY KEY,
  lat REAL NOT NULL,
  lng REAL NOT NULL,
  city TEXT,
  state TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_zip_geo_lat_lng ON zip_geo(lat,lng);
