// Regenerates migrations/0029_zip_geo*.sql from the `zipcodes` package (US ZIP centroids).
// Run: node scripts/build-zip-geo.mjs
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';

const require=createRequire(import.meta.url);
const { codes }=require('zipcodes/lib/codes.js');
const sql=(v)=>"'"+String(v).replace(/'/g,"''")+"'";
const rows=Object.values(codes)
  .filter(z=>z.country==='US'&&/^\d{5}$/.test(z.zip)&&Number.isFinite(z.latitude)&&Number.isFinite(z.longitude))
  .sort((a,b)=>a.zip.localeCompare(b.zip))
  .map(z=>`(${sql(z.zip)},${z.latitude.toFixed(4)},${z.longitude.toFixed(4)},${sql(z.city)},${sql(z.state)})`);

let out=`-- Generated by scripts/build-zip-geo.mjs. US ZIP centroids for distance matching and ZIP->state lookup.
CREATE TABLE IF NOT EXISTS zip_geo (
  zip TEXT PRIMARY KEY,
  lat REAL NOT NULL,
  lng REAL NOT NULL,
  city TEXT,
  state TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_zip_geo_lat_lng ON zip_geo(lat,lng);
`;
writeFileSync(new URL('../migrations/0029_zip_geo.sql',import.meta.url),out);

// Data is split across several migrations so each remote apply stays small.
const PARTS=5,perPart=Math.ceil(rows.length/PARTS);
for(let part=0;part<PARTS;part++){
  const chunk=rows.slice(part*perPart,(part+1)*perPart);
  let sqlOut=`-- Generated by scripts/build-zip-geo.mjs (part ${part+1} of ${PARTS}).\n`;
  for(let i=0;i<chunk.length;i+=400)sqlOut+=`INSERT OR REPLACE INTO zip_geo(zip,lat,lng,city,state) VALUES\n${chunk.slice(i,i+400).join(',\n')};\n`;
  writeFileSync(new URL(`../migrations/0029_zip_geo_part${part+1}.sql`,import.meta.url),sqlOut);
}
console.log(`Wrote ${rows.length} ZIPs`);
